x-uffizzi:
  ingress:
    service: backend
    port: 1337

services:
  backend:
    image: "${BACKEND_IMAGE}"
    environment:
      STRAPI_ADMIN_CLIENT_PREVIEW_SECRET: USGmBGempHrQ9Bu5DhNXBFxa
      DATABASE_CLIENT: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - "1337:1337"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 1000M

  db:
    image: postgres:12-alpine
    platform: linux/amd64
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  strapi-data:
